name: card_settings
description: A flutter package for building card based settings forms. This includes a library of pre-built form field widgets.
version: 0.1.10
author: Jeff Jorczak <jeff@jorczak.com>
homepage: https://github.com/codegrue/card_settings

dependencies:
  flutter:
    sdk: flutter
  flutter_colorpicker: ^0.0.5
  flutter_masked_text: ^0.5.0
  intl: ^0.15.7
  
dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=1.19.0 <3.0.0"

flutter:


# Steps to publish to pub.dartlang.org:
# 1) Run unit tests: "flutter test"
# 2) Verify no documentation issues: "dartdoc --no-auto-include-dependencies "
# 3) Verify no code issues: "flutter analyze"
# 3) Run dartpub review: "pana ."
# 4) Publish: "flutter packages pub publish"
