name: card_settings
description: A flutter package for building card based settings forms. This includes a library of pre-built form field widgets.
version: 0.1.4
author: Jeff Jorczak <jeff@jorczak.com>
homepage: https://github.com/codegrue/card_settings

dependencies:
  flutter:
    sdk: flutter
  flutter_colorpicker: ^0.0.5
  flutter_masked_text: ^0.5.0
  intl: ^0.15.7
  
dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=1.19.0 <3.0.0"

flutter:


# Command Reference
# - To publish to pub.dartlang.org: flutter packages pub publish
# - To generate documentation: dartdoc
