name: card_settings
description: A flutter package for building card based settings forms.
version: 0.1.0
author: Jeff Jorczak <jeff@jorczak.com>
homepage: https://github.com/codegrue/card_settings

dependencies:
  flutter:
    sdk: flutter
  flutter_colorpicker: any
  intl: ^0.15.7
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
